### PR TITLE
Rename iCub-Client -> iCub-HRI

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
To be merged after review.

### CODE REVIEW

**Comment by towardthesea** [comment]
Shall we change this one in [binding dox](https://robotology.github.io/icub-hri/doxygen/doc/html/group__icubclient__bindings.html)
```
You can then append the path of the bindings, the same as you did for YARP (you might want to add this to your .bashrc:

export PYTHONPATH=$PYTHONPATH:/path/to/icub-client/bindings/build
```

**Comment by Tobias-Fischer** [comment]
Hey @towardthesea, thanks for checking :). It should be changed already, isn't it? https://github.com/robotology/icub-hri/pull/42/files#diff-184aaac4a4340ef871a123ca6dcb8eeb

**Comment by towardthesea** [comment]
My bad, wrong branch :smile:

**Comment by Tobias-Fischer** [comment]
Guess this will never happen, so closing here

**Pull request closed without merging**
